[package]
name = "catsay"
version = "0.1.0"
authors = ["lngh <linggih_saputro@srwasia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.15"
colored = "1.7.0"